// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class Hotel
    {
        [JsonProperty("offerDateRange")]
        public OfferDateRange OfferDateRange { get; set; }

        [JsonProperty("destination")]
        public Destination Destination { get; set; }

        [JsonProperty("hotelInfo")]
        public HotelInfo Info { get; set; }

        [JsonProperty("hotelUrgencyInfo")]
        public HotelUrgencyInfo UrgencyInfo { get; set; }

        [JsonProperty("hotelPricingInfo")]
        public HotelPricingInfo PricingInfo { get; set; }

        [JsonProperty("hotelUrls")]
        public HotelUrls Urls { get; set; }
    }
}
