// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class OfferInfo
    {
        [JsonProperty("siteID")]
        public string SiteID { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("userSelectedCurrency")]
        public string UserSelectedCurrency { get; set; }
    }
}
