// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class Offers
    {
        [JsonProperty("Hotel")]
        public Hotel[] Hotels { get; set; }
    }
}
