// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class OfferDateRange
    {
        [JsonProperty("travelStartDate")]
        public int[] TravelStartDate { get; set; }

        [JsonProperty("travelEndDate")]
        public int[] TravelEndDate { get; set; }

        [JsonProperty("lengthOfStay")]
        public int LengthOfStay { get; set; }
    }
}
