// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class Persona
    {
        [JsonProperty("personaType")]
        public string PersonaType { get; set; }
    }
}
