// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class UserInfo
    {
        [JsonProperty("persona")]
        public Persona Persona { get; set; }

        [JsonProperty("userId")]
        public string UserId { get; set; }
    }
}
